### ISSUE TITLE
Disconnect doesn't return the promise.

### ISSUE THREAD

**Issue by takaya-akasaka** [cdimascio/node-mongodb-fixtures#15]
Disconnect doesn't return the promise.
「this._client.close()」have to be returned.

https://github.com/cdimascio/node-mongodb-fixtures/blob/c639b09471ced147a9141533b74f1274ff6c3d57/lib/db.js#L25

**Comment by cdimascio** [comment]
@takaya-akasaka thanks for the issue. `v3.1.2` has a fix to ensure disconnect returns the promise.
