### ISSUE TITLE
Can I have multiple files for same collection

### ISSUE THREAD

**Issue by kkorus** [cdimascio/node-mongodb-fixtures#16]
Can I have multiple files for the same collection? The documentation says that I need a file with the name of the collection like: `users.js` but I want to put them into separate files like:

users.registered.js
users.samples.js
users.expired.js

**Comment by cdimascio** [comment]
You should create a users.js, then have it reference the 3 other files to build and return the data for users collection. You will also want to put the 3 other files in a directory to avoid collections being created for them. That or use a filter.
