### ISSUE TITLE
Fixtures relationship

### ISSUE THREAD

**Issue by rahadi** [cdimascio/node-mongodb-fixtures#27]
I just wonder how to relate two fixtures? lets say i have two schemas (users and comments). A comment document stores user_id as a referecen to user document. how this can be acheived through this lib?

**Comment by darrenwest-allocate** [comment]
There is nothing special for you to do, you would just load all documents. There is no enforcement of referential integrity, by this lib or by mongo.

**Comment by andrew-svirin** [comment]
Can be specified priority of fixtures for loading?

**Comment by darrenwest-allocate** [comment]
it would happen in the order that `fs.readdir` returns files.
If this is deterministic, then you may be able to find a way.

https://github.com/cdimascio/node-mongodb-fixtures/blob/9dd8bae8817fc56f3dfb786568ac91ad705f1e85/lib/index.js#L54

**Comment by andrew-svirin** [comment]
I just used `require()` in related fixture and generated Ids were that I needed. Not sure that it correct for huge files, but in my case it is solution.
