### ISSUE TITLE
MongoError: ns not found

### ISSUE THREAD

**Issue by juank11memphis** [cdimascio/node-mongodb-fixtures#8]
After upgrading to latest version (2.3.3) I started getting this error when calling `fixtures.unload()`:
```
UnhandledPromiseRejectionWarning: MongoError: ns not found
```

The problem gets fixed when downgrading to version `2.2.1`

**Comment by cdimascio** [comment]
Thanks @juank11memphis I'm seeing this too. Seems I flubbed it up
I'll look into it shortly

**Comment by cdimascio** [comment]
It's fixed in v2.3.4

**Comment by juank11memphis** [comment]
Hi @cdimascio thanks a lot for the quick response, it is fix indeed!! :)
